import { Lawyer, CaseType, Testimonial, NewsItem } from "@/types";

export const LAWYERS: Lawyer[] = [
  {
    id: "1",
    name: "Adv. Priya Sharma",
    specialization: ["Property", "Civil"],
    city: "Delhi",
    experience: 14,
    socialScore: 91,
    phone: "+91 98100 11234",
    linkedin: "https://linkedin.com/in/priya-sharma-adv",
    fee: "₹2,000/hr",
    verified: true,
  },
  {
    id: "2",
    name: "Adv. Rohan Mehta",
    specialization: ["Divorce", "Family"],
    city: "Mumbai",
    experience: 9,
    socialScore: 85,
    phone: "+91 98200 55678",
    linkedin: "https://linkedin.com/in/rohan-mehta-adv",
    fee: "₹1,800/hr",
    verified: true,
  },
  {
    id: "3",
    name: "Adv. Kavitha Iyer",
    specialization: ["Criminal", "Civil"],
    city: "Bengaluru",
    experience: 17,
    socialScore: 94,
    phone: "+91 98300 77890",
    linkedin: "https://linkedin.com/in/kavitha-iyer-adv",
    fee: "₹2,500/hr",
    verified: true,
  },
  {
    id: "4",
    name: "Adv. Sanjay Gupta",
    specialization: ["Property", "Corporate"],
    city: "Delhi",
    experience: 22,
    socialScore: 88,
    phone: "+91 98100 22345",
    linkedin: "https://linkedin.com/in/sanjay-gupta-adv",
    fee: "₹3,000/hr",
    verified: true,
  },
  {
    id: "5",
    name: "Adv. Ananya Bose",
    specialization: ["Divorce", "Women Rights"],
    city: "Kolkata",
    experience: 11,
    socialScore: 79,
    phone: "+91 98400 33456",
    linkedin: "https://linkedin.com/in/ananya-bose-adv",
    fee: "₹1,500/hr",
    verified: false,
  },
  {
    id: "6",
    name: "Adv. Vikram Nair",
    specialization: ["Criminal", "Defense"],
    city: "Chennai",
    experience: 19,
    socialScore: 96,
    phone: "+91 98440 44567",
    linkedin: "https://linkedin.com/in/vikram-nair-adv",
    fee: "₹2,800/hr",
    verified: true,
  },
  {
    id: "7",
    name: "Adv. Neha Joshi",
    specialization: ["Civil", "Consumer"],
    city: "Pune",
    experience: 7,
    socialScore: 72,
    phone: "+91 98220 55678",
    linkedin: "https://linkedin.com/in/neha-joshi-adv",
    fee: "₹1,200/hr",
    verified: false,
  },
  {
    id: "8",
    name: "Adv. Arjun Reddy",
    specialization: ["Property", "Real Estate"],
    city: "Hyderabad",
    experience: 13,
    socialScore: 83,
    phone: "+91 98490 66789",
    linkedin: "https://linkedin.com/in/arjun-reddy-adv",
    fee: "₹2,000/hr",
    verified: true,
  },
  {
    id: "9",
    name: "Adv. Sunita Kapoor",
    specialization: ["Family", "Divorce"],
    city: "Delhi",
    experience: 16,
    socialScore: 87,
    phone: "+91 98100 77890",
    linkedin: "https://linkedin.com/in/sunita-kapoor-adv",
    fee: "₹2,200/hr",
    verified: true,
  },
  {
    id: "10",
    name: "Adv. Ravi Krishnan",
    specialization: ["Criminal", "Corporate"],
    city: "Bengaluru",
    experience: 20,
    socialScore: 92,
    phone: "+91 98310 88901",
    linkedin: "https://linkedin.com/in/ravi-krishnan-adv",
    fee: "₹2,600/hr",
    verified: true,
  },
];

export const CASE_TYPES: CaseType[] = [
  {
    id: "property",
    title: "Property Dispute",
    icon: "🏠",
    description: "Resolve ownership, boundary, and title disputes over land and buildings.",
    commonDocuments: ["Sale Deed", "Title Certificate", "Property Tax Receipts", "Survey Report"],
    relevantActs: ["Transfer of Property Act, 1882", "Registration Act, 1908"],
  },
  {
    id: "divorce",
    title: "Divorce & Separation",
    icon: "⚖️",
    description: "Legal guidance for mutual or contested divorce, custody, and alimony.",
    commonDocuments: ["Marriage Certificate", "Identity Proof", "Financial Statements", "Child Birth Certificate"],
    relevantActs: ["Hindu Marriage Act, 1955", "Special Marriage Act, 1954"],
  },
  {
    id: "criminal",
    title: "Criminal Defense",
    icon: "🔒",
    description: "Defend your rights in FIR, bail, and criminal trial proceedings.",
    commonDocuments: ["FIR Copy", "Bail Application", "Witness Statements", "Medical Reports"],
    relevantActs: ["Indian Penal Code, 1860", "Code of Criminal Procedure, 1973"],
  },
  {
    id: "consumer",
    title: "Consumer Complaint",
    icon: "🛒",
    description: "Fight back against defective products, services, and unfair trade practices.",
    commonDocuments: ["Purchase Invoice", "Warranty Card", "Complaint Letter", "Communication Records"],
    relevantActs: ["Consumer Protection Act, 2019"],
  },
  {
    id: "civil",
    title: "Civil Suit",
    icon: "📋",
    description: "Pursue or defend civil claims including contracts, damages, and injunctions.",
    commonDocuments: ["Plaint", "Written Statement", "Evidence Documents", "Affidavits"],
    relevantActs: ["Code of Civil Procedure, 1908", "Indian Contract Act, 1872"],
  },
  {
    id: "landlord",
    title: "Landlord-Tenant",
    icon: "🏢",
    description: "Navigate rent disputes, eviction notices, and tenancy agreement issues.",
    commonDocuments: ["Rent Agreement", "Rent Receipts", "Eviction Notice", "Utility Bills"],
    relevantActs: ["Rent Control Act", "Transfer of Property Act, 1882"],
  },
  {
    id: "inheritance",
    title: "Inheritance & Will",
    icon: "📜",
    description: "Claim rightful inheritance or challenge a disputed will legally.",
    commonDocuments: ["Will Document", "Death Certificate", "Succession Certificate", "Property Documents"],
    relevantActs: ["Hindu Succession Act, 1956", "Indian Succession Act, 1925"],
  },
  {
    id: "workplace",
    title: "Workplace Harassment",
    icon: "💼",
    description: "Seek legal remedy for sexual harassment, wrongful termination, or workplace discrimination.",
    commonDocuments: ["Employment Contract", "Complaint to HR", "Email Records", "Witness Statements"],
    relevantActs: ["POSH Act, 2013", "Industrial Disputes Act, 1947"],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Rajesh Pillai",
    city: "Delhi",
    caseType: "Property Dispute",
    rating: 5,
    text: "VakilConnect helped me find an excellent property lawyer within hours. The AI summary gave me a clear picture of my rights before I even spoke to the lawyer. Highly recommended for anyone dealing with property issues.",
    date: "January 2026",
    initials: "RP",
  },
  {
    id: "2",
    name: "Sneha Agarwal",
    city: "Mumbai",
    caseType: "Divorce",
    rating: 5,
    text: "Going through a divorce is emotionally draining. VakilConnect made the legal side manageable — I found a compassionate and professional lawyer quickly. The social score feature really helped me trust my choice.",
    date: "December 2025",
    initials: "SA",
  },
  {
    id: "3",
    name: "Kiran Rao",
    city: "Bengaluru",
    caseType: "Consumer Complaint",
    rating: 4,
    text: "I was cheated by a builder and had no idea where to start. The platform guided me through the relevant consumer protection laws and connected me with a specialist. My case is now in court.",
    date: "February 2026",
    initials: "KR",
  },
  {
    id: "4",
    name: "Meera Nambiar",
    city: "Chennai",
    caseType: "Landlord-Tenant",
    rating: 5,
    text: "My landlord was trying to evict me illegally. VakilConnect showed me exactly what my rights were under the Rent Control Act. The lawyer I found through here got the eviction notice quashed in 2 weeks.",
    date: "November 2025",
    initials: "MN",
  },
  {
    id: "5",
    name: "Amit Saxena",
    city: "Pune",
    caseType: "Inheritance",
    rating: 4,
    text: "After my father passed, there was a dispute over the ancestral property. VakilConnect's AI guidance helped me understand the Hindu Succession Act clearly. Found a great lawyer who resolved it amicably.",
    date: "January 2026",
    initials: "AS",
  },
  {
    id: "6",
    name: "Priyanka Menon",
    city: "Hyderabad",
    caseType: "Workplace Harassment",
    rating: 5,
    text: "I was hesitant to speak up about workplace harassment. This platform gave me confidence by explaining my rights under the POSH Act. The lawyer was professional and supportive throughout the process.",
    date: "February 2026",
    initials: "PM",
  },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: "1",
    headline: "Supreme Court clarifies property rights of daughters in ancestral property",
    summary:
      "The Supreme Court reaffirmed that daughters have equal coparcenary rights in ancestral Hindu property regardless of whether the father was alive in 2005. This ruling has significant implications for ongoing property disputes across India.",
    date: "March 10, 2026",
    category: "Property Law",
    source: "The Hindu",
  },
  {
    id: "2",
    headline: "Delhi High Court ruling on live-in relationships and maintenance rights",
    summary:
      "The Delhi High Court ruled that partners in long-term live-in relationships are entitled to maintenance rights under the Domestic Violence Act. The judgment sets a new precedent for relationship recognition in Indian law.",
    date: "March 5, 2026",
    category: "Family Law",
    source: "Indian Express",
  },
  {
    id: "3",
    headline: "New consumer protection guidelines for real estate buyers — 2026",
    summary:
      "The Consumer Affairs Ministry issued updated guidelines mandating builders to compensate buyers for project delays exceeding 6 months. The guidelines strengthen enforcement under the Consumer Protection Act, 2019.",
    date: "February 28, 2026",
    category: "Consumer Law",
    source: "Times of India",
  },
  {
    id: "4",
    headline: "Criminal law amendments: key changes to bail provisions under BNSS",
    summary:
      "The Bharatiya Nagarik Suraksha Sanhita introduces new bail provisions that require courts to decide bail applications within 7 days. Defence lawyers say this is a significant step toward reducing undertrial imprisonment.",
    date: "February 20, 2026",
    category: "Criminal Law",
    source: "Bar and Bench",
  },
  {
    id: "5",
    headline: "Landmark divorce ruling: equal division of matrimonial assets upheld",
    summary:
      "The Bombay High Court upheld an equal 50-50 division of matrimonial assets in a contested divorce case, regardless of which spouse earned more. Legal experts say this marks a shift toward equitable matrimonial property laws in India.",
    date: "February 15, 2026",
    category: "Family Law",
    source: "Live Law",
  },
];
